#' .. content for \description{} (no empty lines) ..
#'
#' .. content for \details{} ..
#'
#' @title An example of a roxygen skeleton generated by fnmate
#' @param arg String. Something that points to a data source.
#' @return
#' @author Collin Schwantes
#' @export
get_data <- function(arg) {

  # pretend I pointed to a csv file or URL to get data
  NULL

}
